<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHF12B8e\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHF12B8e/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHF12B8e.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHF12B8e\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerHF12B8e\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'HF12B8e',
    'container.build_id' => '3b0dd76a',
    'container.build_time' => 1547977679,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHF12B8e');
