<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController::createAuthorAction' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::delete' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::login' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::loginAuthor' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::modifie' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::post' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController::sign' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\LogsDemoController::demoAction' => function () {
    return ($this->privates['.service_locator.dOJ.0GD'] ?? $this->load('get_ServiceLocator_DOJ_0GDService.php'));
}, 'App\\Controller\\AdminController:createAuthorAction' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:delete' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:login' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:loginAuthor' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:modifie' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:post' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\AdminController:sign' => function () {
    return ($this->privates['.service_locator.OLaif_L'] ?? $this->load('get_ServiceLocator_OLaifLService.php'));
}, 'App\\Controller\\LogsDemoController:demoAction' => function () {
    return ($this->privates['.service_locator.dOJ.0GD'] ?? $this->load('get_ServiceLocator_DOJ_0GDService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
